- name: Setup NTP
  hosts: ntp_host
  gather_facts: setup_ntp_service | default(True)
  vars:
    SETUP_NTP_SERVICE: "{{setup_ntp_service | default(True)}}"
  roles:
    - role: setup_ntp
      when: SETUP_NTP_SERVICE == True
